### PR TITLE
Remove library's R.string.app_name

### PR DESCRIPTION
**Pull request by DeweyReed**
The library's `R.string.app_name` is redundant because it isn't used and the app defines its own `app_name` anyway. But it has a side effect.

If I use this library in an android library module which doesn't define `app_name`, when I run the library module's instrumented tests, the library module's APK that is installed on the device will be named `Secure Device Storage` which is misleading.

### CODE REVIEW

**Comment by luckyhandler** [comment]
Hi Dewey, makes sense. Thanks for your contribution. Just give me a little time for merging the PR.

**Review by luckyhandler — APPROVED** [review]

**Comment by luckyhandler** [comment]
Hey @DeweyReed Could you change your PR to be merged into develop, please?

**Review by luckyhandler — CHANGES_REQUESTED** [review]
Please change the target branch to develop

**Comment by DeweyReed** [comment]
@luckyhandler I've changed the target branch to develop but it includes many other commits. Would it be better if I create another PR based on develop branch?

**Comment by luckyhandler** [comment]
yeah, this would be great @DeweyReed

**Pull request closed without merging**
